// The dispatchable command catalog (AC-004: advertised == dispatchable). One list, single-sourced:
// the dispatcher routes to each command's run(), `help` renders the `description`s, and per-command
// `<cmd> --help` renders the `usage` lines. The parity test cross-checks `name` against the
// useCases/ files. Exactly the M1 reconcile-only surface — no agent verbs, no garden.
export const COMMAND_CATALOG = [
    {
        name: 'init',
        description: 'Seed this repo for the personal harness — config, AGENTS.md, skills dirs',
        usage: [
            'suspec init',
            '  (no flag)                   write suspec.config.json (defaults + detected setup), seed AGENTS.md',
            '                              if absent, create .agents/skills/ + the .claude/skills symlink,',
            '                              gitignore .worktrees/ — nothing else lands in the repo',
            '  --yes                       also link CLAUDE.md → AGENTS.md (accept every offer)',
            '  --json · -i                 machine output · interactive flow (prompts for the CLAUDE.md link)',
            '  artifacts live in your personal store, outside the repo; the store is never touched here',
        ],
    },
    {
        name: 'update',
        description: 'Check kit drift, or refresh kit-managed templates (conflict-safe)',
        usage: [
            'suspec update [--check | --write]',
            '  --check (default)           compare .agents/.suspec-version to the kit VERSION; writes nothing',
            '  --write | --apply           refresh the kit-owned templates (per the kit manifest) + re-stamp the pin',
            '  --on-conflict backup|overwrite|skip   handle a customized kit file (default: backup → *.suspec-bak)',
            '  --from <path|url>           kit source (default: the suspec-starter-kit on GitHub)',
            '  --json                      machine output',
            '  --check: exit 0 up-to-date · 1 behind · 2 error · --write: 1 if files need reconciling',
            '  skills are not refreshed here — they install globally (npx skills add jcosta33/suspec-skills -g)',
        ],
    },
    {
        name: 'check',
        description: "Validate one artifact by its type, or lint the store's artifacts for this repo",
        usage: [
            'suspec check [file]',
            "  (no file)                   lint the store's artifacts — runs, specs, reviews, evidence records",
            '  <file>                      validate by frontmatter type: spec, review (C012/C013), or change-plan (C010/C011); exit 0 clean · 1 warnings · 2 error',
            '  --staleness                 advisory: which snapshotted specs drifted since their snapshot SHA',
            '  --json · -i                 machine output · interactive flow',
        ],
    },
    {
        name: 'worktree',
        description: 'Create / list / remove / prune isolated task worktrees',
        usage: [
            'suspec worktree <create|list|remove|prune> [slug]',
            '  create <slug> [--task <t>] [--base <branch>]   worktree on suspec/<slug>[/<task>]',
            '  remove <slug> [--task <t>] [--force]           tear one down',
            '  list · prune                                   show / clear stale worktrees',
            '  --json · -i                                    machine output · interactive flow',
        ],
    },
    {
        name: 'status',
        description: 'The store summary — runs, specs, and what needs attention',
        usage: [
            'suspec status',
            '  (no flag)                   active + archived store artifacts, plus the attention ranking',
            '  --json · -i                 machine output · interactive view',
        ],
    },
    {
        name: 'clean',
        description: 'Store hygiene — delete archived artifacts past retention (= `store gc`)',
        usage: [
            'suspec clean',
            '  (no flag)                   delete ONLY archive/ items past retention_days (default 30)',
            '  --json                      machine output',
        ],
    },
    {
        name: 'stamp',
        description: 'Stamp a spec snapshot SHA (enables `check --staleness`)',
        usage: [
            'suspec stamp <ref>',
            '  <spec id|slug>              write snapshot: HEAD (enables `check --staleness`)',
            '  --repo <path>               stamp against a separate code repo · --json',
        ],
    },
    {
        name: 'review',
        description: 'Reconcile a store run against its spec — artifact lint + evidence per AC (no verdict)',
        usage: [
            'suspec review <RUN>',
            '  <RUN>                       a store run slug (run-<RUN>.md)',
            '  lint: the run record, its driving spec, its review packet, every evidence record',
            '  reconcile: each spec AC against the evidence (verified / stale / failing / missing)',
            '  --json · -i                 machine output · interactive flow',
            '  surfaces facts + routes; the human owns the result — `suspec done` closes the gate',
        ],
    },
    {
        name: 'new',
        description: 'Cut a store task slice from a store spec, or scaffold a change plan',
        usage: [
            'suspec new <task|change-plan>',
            '  task --from <SPEC> [--scope AC-001,AC-002] [--id <TASK-id>]   cut a slice into the store (scope never invented)',
            '  change-plan <slug>                              scaffold a draft change plan (migrations/rewrites)',
            '  --id <TASK-id>                                  name a 2nd+ task from one spec (else TASK-<spec-slug>)',
            '  --force                                         re-cut over an existing task slice (e.g. to add --scope)',
            '  --json · -i                                     machine output · interactive flow',
            '  specs scaffold via `suspec write spec "<intent>"` (the one store scaffold)',
        ],
    },
    {
        name: 'write',
        description: 'Scaffold a draft store spec from a one-line intent — optionally dispatch the spec author',
        usage: [
            'suspec write spec "<one-line intent>"',
            '  "<intent>"                  seeds spec-<slug>.md in the store: status draft, base_sha = repo HEAD,',
            '                              one empty AC + a Verify placeholder — the CLI authors NO requirements',
            '  --launch                    dispatch the spec-author prompt (a pointer at the store spec) to the runner',
            '  --runner <name>             the runner from suspec.config.json runners (built-ins: claude, codex)',
            '  --json                      machine output',
            '  then: suspec work <SPEC-id>',
        ],
    },
    {
        name: 'pull',
        description: 'Snapshot a ticket into the store — verbatim capture only, never a spec',
        usage: [
            'suspec pull <ref>',
            '  <ref>                       a gh issue (number/owner-repo#N/URL — fetched via gh), or any tracker ref',
            '  --force                     overwrite an existing intake-<slug>.md (else no-clobber)',
            '  --json                      machine output',
            '  writes one store intake snapshot (paste placeholder when no fetch); the recorded url',
            '  makes it re-pullable after a store wipe. Capture only — `suspec fix #N` scaffolds + launches',
        ],
    },
    {
        name: 'promote',
        description: 'Promote a store finding to a GitHub issue (evidence digest + provenance), then archive it',
        usage: [
            'suspec promote <FIND>',
            '  <FIND>                      a finding id (frontmatter `id:`) or store filename (finding-*.md)',
            '  --json                      machine output',
            '  the issue body carries the finding + the run evidence digest + the provenance label;',
            '  the issue number is stamped into the finding, which then retires to archive/',
            '  exit 0 promoted · 1 gh missing/failing (named; nothing changed) · 2 unknown finding',
        ],
    },
    {
        name: 'fix',
        description: 'Scaffold a store fix-spec from a finding or gh issue, then launch it via the work pipeline',
        usage: [
            'suspec fix <FIND-id | #issue>',
            '  <FIND-id>                   a finding id / store filename (archive/ included)',
            '  #<issue>                    a GitHub issue number, fetched via gh (survives a store wipe)',
            '  --no-launch                 scaffold spec-fix-<slug>.md only; print its path',
            '  --runner <name> · --base <branch> · --anyway · --json   forwarded to the work pipeline',
            '  scaffolds base_sha = repo HEAD (+ affected_areas from the finding), then hands off to `work`',
        ],
    },
    {
        name: 'store',
        description: 'Store maintenance — doctor (reconcile), list, gc (retention), purge (whole store)',
        usage: [
            'suspec store <doctor|list|gc|purge>',
            '  doctor                      archive spec/run artifacts whose branch merged, worktree vanished,',
            '                              or PR closed (git/GitHub truth; never deletes; orphans listed; exit 0)',
            '  list                        active + archived artifacts with per-artifact age',
            '  gc                          delete ONLY archive/ items past retention_days (default 30)',
            '  purge [--force]             delete the repo’s whole store — type the repo name, or --force',
            '  --json                      machine output',
        ],
    },
    {
        name: 'run',
        description: 'Launch a prepared task on an agent in its worktree — records the launch (no verdict)',
        usage: [
            'suspec run <task> --agent <name>',
            '  <task>                      the task to launch — its worktree must already exist (suspec worktree create)',
            '  --agent <name>              the adapter from .suspec/config.yaml (else agents.default)',
            '  --json                      machine output',
            '  launches the agent + records the launch envelope under .suspec/work/; never the board, never a verdict',
        ],
    },
    {
        name: 'work',
        description:
            'Work a store spec: create/reuse its worktree, set up, launch a runner pointed at the store (no verdict)',
        usage: [
            'suspec work <SPEC>',
            '  <SPEC>                      a spec id/slug, resolved against the store (spec-*.md)',
            '  --runner <name>             the runner from suspec.config.json runners (built-ins: claude, codex)',
            '  --base <branch>             the worktree base (else the current branch)',
            '  --anyway                    launch despite recorded spec staleness',
            '  --attach                    a live run: print the runner-native attach hint (dispatches nothing)',
            '  --second-worktree           a live run: launch in a suffixed worktree with its own run file',
            '  --dry-run                   resolve + print the plan and prompt; launch nothing, write nothing',
            '  --json                      machine output',
            '  by hand (no CLI): create the worktree, cd in, run your agent against the store spec',
        ],
    },
    {
        name: 'evidence',
        description: 'Capture cli-verified evidence: run a verify command in the run worktree, record it in the store',
        usage: [
            'suspec evidence add <RUN> --ac <AC-id> -- <command…>',
            '  add <RUN>                   the store run the evidence belongs to (run-<RUN>.md)',
            '  --ac <AC-id>                the acceptance criterion the evidence maps to (e.g. AC-003)',
            '  -- <command…>               the command to run (in the run worktree; bare binary + args, no shell)',
            '  --json                      machine output',
            '  exit mirrors the command (0/1) — the record is written either way; raw output stays in the store',
        ],
    },
    {
        name: 'done',
        description: 'The strict gate: lint the run artifacts, gate every AC on cli-verified evidence, digest + triage',
        usage: [
            'suspec done <RUN>',
            '  <RUN>                       the store run to close (run-<RUN>.md)',
            '  --accept-failing "<why>"    accept gate gaps explicitly — the reason lands in the digest + run file',
            '  --allow-agent-evidence      let provenance: agent evidence count (labeled in the digest)',
            '  --discard-critical <id>     allow triage to discard the named critical finding',
            '  --json                      machine output (defers findings triage with an expiry stamp)',
            '  exit 0 gate satisfied/accepted · 1 gate blocked (gaps listed) · 2 usage / lint hard-error',
        ],
    },
    {
        name: 'check-my-work',
        description:
            'The middle tier: gate the current repo diff (config `verify`) + dispatch one adversarial reviewer',
        usage: [
            'suspec check-my-work "<one-line intent>"',
            '  "<intent>"                  what the reviewer reviews the current diff against',
            '  (diff base)                 merge-base with the default branch; staged+unstaged when already on it',
            '  --save                      record a check run + evidence records in the store (else artifact-free)',
            '  --no-review                 gate only — no reviewer dispatched',
            '  --dry-run                   print the plan + reviewer prompt; run nothing, write nothing',
            '  --runner <name>             the reviewer runner (else runners.default) · --json',
            '  exit mirrors the gate: 0 verify passed/none declared · 1 a verify command failed · 2 usage/launch failure',
        ],
    },
    {
        name: 'next',
        description: 'The single most actionable store item — live runs, gate gaps, triage debt, ready specs',
        usage: [
            'suspec next',
            '  (no flag)                   print THE top item (+ the ambient decay line)',
            '  --json                      the full ranking, machine-readable',
            '  reads only the store + local git state — zero network, zero gh; writes nothing',
        ],
    },
    {
        name: 'show',
        description: 'Project a parsed artifact as JSON — task, spec, review, or the checks contract (read-only)',
        usage: [
            'suspec show <task|spec|review|checks> [ref]',
            '  task <stem>                 the parsed task packet (scope, affected areas, claimed changes)',
            '  spec <id|path>              the parsed spec (frontmatter, requirements + verify commands)',
            '  review <stem>               the parsed review packet (status, coverage rows, verify blocks)',
            '  checks                      the checks contract (version + the core checks)',
            '  --json                      machine output; reads only, renders no verdict',
        ],
    },
    {
        name: 'agents',
        description: 'Project Claude Code agent definitions into another runner (Codex TOML)',
        usage: [
            'suspec agents emit --codex [--from <dir>]',
            '  emit --codex                generate .codex/agents/*.toml from the agent definitions',
            '  --from <dir>                the agent *.md defs (default: ./.claude/agents, else ../suspec-agents/agents)',
            '  --force                     overwrite existing generated .toml files (they regenerate)',
            '  --json                      machine output',
            '  prose discipline only — tool-scoping + hooks are Claude-Code-only and do NOT travel',
        ],
    },
    {
        name: 'help',
        description: 'Show this command reference',
        usage: ['suspec help', 'suspec --help · suspec --version'],
    },
] as const;
