import { describe, it, expect } from 'vitest';

import { parse_agent_def, escape_toml_multiline, render_codex_agent } from '../useCases/codexToml.ts';

const AGENT = `---
name: swarm-reviewer
description: >-
  Independently review a finished Swarm task, read-only: re-run the Verify checks
  and draft a review packet WITHOUT issuing the verdict.
tools: Read, Grep, Glob, Bash
---

# swarm-reviewer (Claude Code)

Re-run the checks yourself. Never issue the result.
`;

describe('parse_agent_def', () => {
    it('extracts name, tools, the folded description, and the body', () => {
        const def = parse_agent_def(AGENT);
        expect(def).not.toBeNull();
        expect(def?.name).toBe('swarm-reviewer');
        expect(def?.tools).toBe('Read, Grep, Glob, Bash');
        // the `>-` folded block is joined to one line (no leading `>-`, no newlines)
        expect(def?.description).toBe(
            'Independently review a finished Swarm task, read-only: re-run the Verify checks and draft a review packet WITHOUT issuing the verdict.'
        );
        expect(def?.body).toBe('# swarm-reviewer (Claude Code)\n\nRe-run the checks yourself. Never issue the result.');
    });

    it('returns null for a file with no frontmatter or no name', () => {
        expect(parse_agent_def('# just a doc\n')).toBeNull();
        expect(parse_agent_def('---\ntools: Read\n---\nbody')).toBeNull(); // no name
        expect(parse_agent_def('---\nname: x\nunterminated')).toBeNull(); // no closing fence
    });

    it('handles a scalar (non-folded) description + a def with no tools', () => {
        const def = parse_agent_def('---\nname: x\ndescription: a one-liner\n---\nbody\n');
        expect(def?.description).toBe('a one-liner');
        expect(def?.tools).toBe('');
    });

    it('handles a def with no description key at all', () => {
        const def = parse_agent_def('---\nname: x\ntools: Read\n---\nbody\n');
        expect(def?.name).toBe('x');
        expect(def?.description).toBe('');
    });

    it('tolerates a leading UTF-8 BOM before the frontmatter fence', () => {
        const def = parse_agent_def('\uFEFF---\nname: x\ndescription: d\n---\nbody\n');
        expect(def?.name).toBe('x');
    });

    it('strips surrounding YAML quotes from a name so the filename is clean', () => {
        expect(parse_agent_def('---\nname: "swarm-x"\n---\nb\n')?.name).toBe('swarm-x');
        expect(parse_agent_def("---\nname: 'swarm-y'\n---\nb\n")?.name).toBe('swarm-y');
    });
});

describe('escape_toml_multiline', () => {
    it('escapes backslashes and quotes so no run of three quotes can close the delimiter', () => {
        expect(escape_toml_multiline('a \\ b')).toBe('a \\\\ b');
        expect(escape_toml_multiline('"""')).toBe('\\"\\"\\"');
        expect(escape_toml_multiline('say "hi"')).toBe('say \\"hi\\"');
    });

    it('escapes raw control chars (e.g. an ANSI escape, BEL, NUL) to \\uXXXX, leaving tab + newline raw', () => {
        expect(escape_toml_multiline('a\x1bb')).toBe('a\\u001bb'); // ESC
        expect(escape_toml_multiline('a\x07b')).toBe('a\\u0007b'); // BEL
        expect(escape_toml_multiline('a\x00b')).toBe('a\\u0000b'); // NUL
        expect(escape_toml_multiline('a\tb\nc')).toBe('a\tb\nc'); // tab + newline stay raw (TOML allows them)
    });
});

describe('render_codex_agent', () => {
    it('emits a parseable TOML doc: honesty header + developer_instructions = the body', () => {
        const toml = render_codex_agent(parse_agent_def(AGENT)!);
        expect(toml).toContain('developer_instructions = """');
        expect(toml).toContain('# swarm-reviewer — generated by');
        expect(toml).toContain('ADR-0098');
        // the honest scope: tool-scoping is named as Claude-Code-only and NOT travelling
        expect(toml).toContain('Tool-scoping');
        expect(toml).toContain('Source tools (Claude-Code-enforced, NOT enforced here): Read, Grep, Glob, Bash');
        // the body lands inside the multiline string
        expect(toml).toContain('Re-run the checks yourself. Never issue the result.');
    });

    it('a def with no tools states that, rather than an empty allowlist', () => {
        const toml = render_codex_agent({ name: 'x', description: 'd', tools: '', body: 'b' });
        expect(toml).toContain('Source declares no tool allowlist.');
    });

    it('a body carrying backslashes + triple-quotes survives — the emitted TOML is still valid', () => {
        const toml = render_codex_agent({
            name: 'x',
            description: 'd',
            tools: 'Read',
            body: 'has "quotes" and \\ backslash and """ triple',
        });
        // the dangerous sequences are escaped so the multiline string never closes early
        expect(toml).toContain('has \\"quotes\\" and \\\\ backslash and \\"\\"\\" triple');
        // and the closing delimiter is intact
        expect(toml.trimEnd().endsWith('"""')).toBe(true);
    });

    it('round-trips the body byte-for-byte — no trailing newline is inserted before the closing delimiter', () => {
        const toml = render_codex_agent({ name: 'x', description: 'd', tools: 'Read', body: 'line one\nlast line' });
        // the closing `"""` follows the last body char directly (no `\n` inserted), so the parsed value
        // is the trimmed body exactly, not body + "\n".
        expect(toml).toContain('"""\nline one\nlast line"""');
        expect(toml).not.toContain('last line\n"""');
    });
});
