// Codex agent-definition emission (ADR-0098). Projects a Claude Code agent definition (the
// swarm-agents `agents/*.md` form — YAML frontmatter `name` / `description` / `tools` + a markdown
// body that is the system prompt) into an OpenAI Codex `.codex/agents/<name>.toml`. PURE string work:
// parse in, TOML out — the engine (emitAgents) does the filesystem.
//
// HONEST SCOPE (ADR-0098): only the PROSE discipline ports. The source's `tools` allowlist and any
// PreToolUse/Subagent hooks are Claude-Code-only structural enforcement — they do NOT travel to Codex.
// Every emitted file carries a header saying so, so a Codex adopter is never misled that tool-scoping
// came along. Hand-rolled TOML (no dependency — swarm-cli's tree stays tiny); the only serialization
// needed is a multiline string + a comment header.

export type AgentDef = Readonly<{
    name: string;
    description: string; // folded to a single line (best-effort; metadata for the header only)
    tools: string; // the raw `tools:` allowlist value, or '' when none (Claude-Code-enforced, not ported)
    body: string; // everything after the closing frontmatter fence — the system prompt
}>;

// Parse the swarm-agents agent-definition form. A light scanner (not full YAML): `name`/`tools` are
// scalars; `description` is commonly a folded block (`>-` then indented continuation lines), so its
// continuation lines (more-indented than the key) are joined with spaces. The body is everything after
// the closing `---`. Returns null when there is no frontmatter or no `name` (not an agent def).
export function parse_agent_def(source: string): AgentDef | null {
    const text = source.charCodeAt(0) === 0xfeff ? source.slice(1) : source;
    const lines = text.split(/\r\n|[\r\n]/);
    if (lines[0] !== '---') {
        return null;
    }
    let end = 1;
    while (end < lines.length && lines[end] !== '---') {
        end += 1;
    }
    if (end >= lines.length) {
        return null; // unterminated frontmatter
    }
    const fm = lines.slice(1, end);
    const body = lines
        .slice(end + 1)
        .join('\n')
        .trim();

    const scalar = (key: string): string => {
        const match = fm.find((line) => line.startsWith(`${key}:`));
        if (match === undefined) {
            return '';
        }
        // Strip one matched pair of surrounding YAML quotes so `name: "swarm-x"` yields `swarm-x` (a clean
        // filename), not a literally-quoted `"swarm-x"`.
        return match
            .slice(match.indexOf(':') + 1)
            .trim()
            .replace(/^(['"])(.*)\1$/, '$2');
    };

    const name = scalar('name');
    if (name === '') {
        return null;
    }

    // `description` may be a folded block: the key line is `description: >-` (or just `description:`),
    // followed by indented continuation lines until the next top-level `key:` line.
    let description = scalar('description').replace(/^[>|][+-]?\s*$/, '');
    const descIndex = fm.findIndex((line) => line.startsWith('description:'));
    if (descIndex !== -1) {
        const continuation: string[] = [];
        for (let i = descIndex + 1; i < fm.length; i += 1) {
            if (/^\w[\w-]*:/.test(fm[i])) {
                break; // the next top-level key ends the folded block
            }
            continuation.push(fm[i].trim());
        }
        const folded = continuation.join(' ').trim();
        if (folded !== '') {
            description = folded;
        }
    }

    return { name, description, tools: scalar('tools'), body };
}

// Escape an arbitrary string for a TOML multiline basic string (`"""…"""`):
//   1. backslash → `\\` (first, so later-introduced escapes are not double-escaped);
//   2. every `"` → `\"` so no run of three `"` can ever close the delimiter early;
//   3. raw control chars (U+0000–U+001F except tab + newline, plus a lone CR) → `\uXXXX` — TOML forbids
//      them raw, so a body carrying e.g. an ANSI escape (U+001B) still emits valid, parseable TOML.
// The render below places the closing `"""` directly after the (escaped) body — with no inserted
// trailing newline — so the parsed `developer_instructions` is the trimmed body byte-for-byte.
// eslint-disable-next-line no-control-regex -- intentionally matching control chars to escape them
const CONTROL_CHARS = /[\x00-\x08\x0b-\x1f]/g;

export function escape_toml_multiline(value: string): string {
    return value
        .replace(/\\/g, '\\\\')
        .replace(/"/g, '\\"')
        .replace(CONTROL_CHARS, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, '0')}`);
}

export function render_codex_agent(def: AgentDef): string {
    const toolsNote =
        def.tools === ''
            ? '# Source declares no tool allowlist.'
            : `# Source tools (Claude-Code-enforced, NOT enforced here): ${def.tools}`;
    const header = [
        `# ${def.name} — generated by \`swarm agents emit --codex\` from a Claude Code agent definition.`,
        '# PORTABILITY (honest scope, ADR-0098): this carries the prose discipline only.',
        '# Tool-scoping (the source `tools` allowlist) and PreToolUse/Subagent hooks are Claude-Code-only',
        '# and do NOT travel — Codex reads `developer_instructions` as the system prompt; grant/deny tools',
        '# in your Codex config. Do not hand-edit: re-run the emitter to regenerate.',
        toolsNote,
    ].join('\n');

    // `"""\n` opens (TOML trims that first newline); the closing `"""` follows the escaped body with NO
    // inserted newline, so the parsed value is the trimmed body byte-for-byte (a body ending in `\` or a
    // quote is already escaped, so it can never merge with the closing delimiter).
    return `${header}\n\ndeveloper_instructions = """\n${escape_toml_multiline(def.body)}"""\n`;
}
